name: article_dataset_builder

services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    init: true
    ulimits:
      core: 0
    ports:
      - 8070:8070
    command: 
    healthcheck:
      test: "apt-get update && apt-get install -y curl && curl -f http://localhost:8070"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 15s
  harvester:
    build: .
    image: article_dataset_builder-harvester:latest
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      grobid:
        condition: service_healthy